# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.24

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.24.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.24.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zsolti/Desktop/mosze_leadas/mosze-semester-project-bagira

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zsolti/Desktop/mosze_leadas/mosze-semester-project-bagira

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.24.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.24.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zsolti/Desktop/mosze_leadas/mosze-semester-project-bagira/CMakeFiles /Users/zsolti/Desktop/mosze_leadas/mosze-semester-project-bagira//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zsolti/Desktop/mosze_leadas/mosze-semester-project-bagira/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named snowattack-game

# Build rule for target.
snowattack-game: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 snowattack-game
.PHONY : snowattack-game

# fast build rule for target.
snowattack-game/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/build
.PHONY : snowattack-game/fast

#=============================================================================
# Target rules for targets named runTests

# Build rule for target.
runTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 runTests
.PHONY : runTests

# fast build rule for target.
runTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/build
.PHONY : runTests/fast

Test.o: Test.cpp.o
.PHONY : Test.o

# target to build an object file
Test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/Test.cpp.o
.PHONY : Test.cpp.o

Test.i: Test.cpp.i
.PHONY : Test.i

# target to preprocess a source file
Test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/Test.cpp.i
.PHONY : Test.cpp.i

Test.s: Test.cpp.s
.PHONY : Test.s

# target to generate assembly for a file
Test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/Test.cpp.s
.PHONY : Test.cpp.s

include/Character.o: include/Character.cpp.o
.PHONY : include/Character.o

# target to build an object file
include/Character.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Character.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Character.cpp.o
.PHONY : include/Character.cpp.o

include/Character.i: include/Character.cpp.i
.PHONY : include/Character.i

# target to preprocess a source file
include/Character.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Character.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Character.cpp.i
.PHONY : include/Character.cpp.i

include/Character.s: include/Character.cpp.s
.PHONY : include/Character.s

# target to generate assembly for a file
include/Character.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Character.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Character.cpp.s
.PHONY : include/Character.cpp.s

include/Game.o: include/Game.cpp.o
.PHONY : include/Game.o

# target to build an object file
include/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Game.cpp.o
.PHONY : include/Game.cpp.o

include/Game.i: include/Game.cpp.i
.PHONY : include/Game.i

# target to preprocess a source file
include/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Game.cpp.i
.PHONY : include/Game.cpp.i

include/Game.s: include/Game.cpp.s
.PHONY : include/Game.s

# target to generate assembly for a file
include/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Game.cpp.s
.PHONY : include/Game.cpp.s

include/Option.o: include/Option.cpp.o
.PHONY : include/Option.o

# target to build an object file
include/Option.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Option.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Option.cpp.o
.PHONY : include/Option.cpp.o

include/Option.i: include/Option.cpp.i
.PHONY : include/Option.i

# target to preprocess a source file
include/Option.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Option.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Option.cpp.i
.PHONY : include/Option.cpp.i

include/Option.s: include/Option.cpp.s
.PHONY : include/Option.s

# target to generate assembly for a file
include/Option.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Option.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Option.cpp.s
.PHONY : include/Option.cpp.s

include/Page.o: include/Page.cpp.o
.PHONY : include/Page.o

# target to build an object file
include/Page.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Page.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Page.cpp.o
.PHONY : include/Page.cpp.o

include/Page.i: include/Page.cpp.i
.PHONY : include/Page.i

# target to preprocess a source file
include/Page.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Page.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Page.cpp.i
.PHONY : include/Page.cpp.i

include/Page.s: include/Page.cpp.s
.PHONY : include/Page.s

# target to generate assembly for a file
include/Page.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/include/Page.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/runTests.dir/build.make CMakeFiles/runTests.dir/include/Page.cpp.s
.PHONY : include/Page.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/snowattack-game.dir/build.make CMakeFiles/snowattack-game.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... runTests"
	@echo "... snowattack-game"
	@echo "... Test.o"
	@echo "... Test.i"
	@echo "... Test.s"
	@echo "... include/Character.o"
	@echo "... include/Character.i"
	@echo "... include/Character.s"
	@echo "... include/Game.o"
	@echo "... include/Game.i"
	@echo "... include/Game.s"
	@echo "... include/Option.o"
	@echo "... include/Option.i"
	@echo "... include/Option.s"
	@echo "... include/Page.o"
	@echo "... include/Page.i"
	@echo "... include/Page.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

